In [183]:
# Import Required Libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

print("Libraries imported successfully")

Libraries imported successfully

## Load all required tables

In [184]:
# Load dataset 'loads'
df_loads = pd.read_csv("loads.csv")

# Preview dataset 'loads'
df_loads.head(10)

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
0,LOAD00000001,CUST00183,RTE00019,2022-01-01,Dry Van,19178,13,3045.23,406.72,100,Completed,Spot
1,LOAD00000002,CUST00076,RTE00058,2022-01-01,Dry Van,27761,22,1224.48,98.61,0,Completed,Dedicated
2,LOAD00000003,CUST00027,RTE00048,2022-01-01,Refrigerated,35594,16,7171.12,792.88,0,Completed,Spot
3,LOAD00000004,CUST00088,RTE00013,2022-01-01,Refrigerated,33274,10,1308.20,141.33,50,Completed,Spot
4,LOAD00000005,CUST00185,RTE00020,2022-01-01,Dry Van,40257,10,3317.18,738.48,0,Completed,Spot
5,LOAD00000006,CUST00193,RTE00004,2022-01-01,Refrigerated,34671,10,3582.78,383.23,75,Completed,Spot
6,LOAD00000007,CUST00169,RTE00038,2022-01-01,Dry Van,14530,4,3872.46,314.64,150,Completed,Contract
7,LOAD00000008,CUST00049,RTE00016,2022-01-01,Refrigerated,16927,26,5914.90,463.93,100,Completed,Spot
8,LOAD00000009,CUST00075,RTE00025,2022-01-01,Refrigerated,38964,3,4759.42,565.38,150,Completed,Dedicated
9,LOAD00000010,CUST00079,RTE00025,2022-01-01,Refrigerated,29233,8,5723.39,565.38,50,Completed,Dedicated

In [185]:
# Load dataset 'trips'
df_trips = pd.read_csv ("trips.csv")

# Preview dataset 'trips'
df_trips. head (10)

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
0,TRIP00000001,LOAD00000001,DRV00117,TRK00035,TRL00167,2022-01-01,1314,26.2,183.8,7.15,3.5,Completed
1,TRIP00000002,LOAD00000002,DRV00141,TRK00108,TRL00082,2022-01-01,515,8.6,93.6,5.50,8.3,Completed
2,TRIP00000003,LOAD00000003,DRV00032,TRK00031,TRL00138,2022-01-01,2509,45.0,339.1,7.40,12.0,Completed
3,TRIP00000004,LOAD00000004,DRV00083,TRK00105,TRL00018,2022-01-01,717,11.1,110.3,6.50,9.6,Completed
4,TRIP00000005,LOAD00000005,DRV00044,TRK00076,TRL00054,2022-01-01,2243,35.0,328.9,6.82,11.6,Completed
5,TRIP00000006,LOAD00000006,DRV00120,TRK00062,TRL00007,2022-01-01,1977,39.4,358.8,5.51,6.6,Completed
6,TRIP00000007,LOAD00000007,DRV00055,TRK00002,TRL00093,2022-01-01,1350,20.9,230.8,5.85,2.3,Completed
7,TRIP00000008,LOAD00000008,DRV00065,TRK00035,TRL00148,2022-01-01,2748,50.5,437.6,6.28,10.5,Completed
8,TRIP00000009,LOAD00000009,DRV00129,TRK00014,TRL00083,2022-01-01,3226,51.4,465.5,6.93,4.1,Completed
9,TRIP00000010,LOAD00000010,DRV00029,TRK00116,TRL00126,2022-01-01,3388,60.2,460.3,7.36,5.7,Completed

In [186]:
# Load dataset 'fuel_purchases'
df_fuel_pur = pd.read_csv ("fuel_purchases.csv")

# Preview dataset 'fuel_purchases'
df_fuel_pur. head (10)

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
0,FUEL00000001,TRIP00051284,TRK00045,DRV00102,2023-10-22 05:00:00,Columbus,MN,131.6,3.399,447.31,FC567161
1,FUEL00000002,TRIP00073723,TRK00013,NaN,2024-08-04 08:00:00,New York,AZ,139.9,3.180,444.88,FC717910
2,FUEL00000003,TRIP00018286,TRK00024,DRV00142,2022-08-23 13:00:00,Seattle,NE,189.3,3.804,720.10,FC912816
3,FUEL00000004,TRIP00008465,TRK00018,DRV00047,2022-04-20 00:00:00,Memphis,NY,130.7,3.579,467.78,FC776357
4,FUEL00000005,TRIP00069700,TRK00054,NaN,2024-06-13 09:00:00,Columbus,AZ,185.3,3.422,634.10,FC391024
5,FUEL00000006,TRIP00062650,TRK00012,DRV00104,2024-03-18 23:00:00,Dallas,NY,182.2,3.494,636.61,FC277504
6,FUEL00000007,TRIP00000851,TRK00072,DRV00127,2022-01-11 21:00:00,Miami,TX,146.3,3.914,572.62,FC256663
7,FUEL00000008,TRIP00012033,TRK00073,DRV00084,2022-06-06 00:00:00,Phoenix,PA,113.3,4.471,506.56,FC543608
8,FUEL00000009,TRIP00023596,TRK00101,DRV00080,2022-10-28 02:00:00,Miami,NC,127.0,4.445,564.51,FC484857
9,FUEL00000010,TRIP00037859,TRK00085,DRV00002,2023-04-30 09:00:00,Dallas,MO,134.7,3.357,452.19,FC753360

In [187]:
# Load dataset 'maintenance_records'
df_main_rec = pd.read_csv ("maintenance_records.csv")

# Preview dataset 'maintenance_records'
df_main_rec. head (10)

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
0,MAINT00000001,TRK00085,2022-01-01,Inspection,400255,7.8,781.42,10.41,791.83,Kansas City,22.2,Emergency Inspection
1,MAINT00000002,TRK00041,2022-01-01,Tire,268041,0.9,80.91,3207.16,3288.07,Seattle,8.0,Scheduled Tire
2,MAINT00000003,TRK00090,2022-01-01,Preventive,698915,7.2,733.18,1570.57,2303.75,Miami,16.5,Routine Preventive
3,MAINT00000004,TRK00056,2022-01-02,Inspection,416522,2.8,298.80,67.48,366.28,Kansas City,34.6,Emergency Inspection
4,MAINT00000005,TRK00029,2022-01-02,Repair,179968,4.6,409.08,982.59,1391.67,Omaha,4.4,Emergency Repair
5,MAINT00000006,TRK00120,2022-01-02,Preventive,680507,5.0,498.12,3029.54,3527.66,Omaha,43.5,Scheduled Preventive
6,MAINT00000007,TRK00017,2022-01-02,Repair,599078,0.9,83.38,1098.90,1182.28,Denver,34.8,Emergency Repair
7,MAINT00000008,TRK00038,2022-01-03,Tire,605379,7.1,785.79,1483.25,2269.04,Miami,3.9,Scheduled Tire
8,MAINT00000009,TRK00054,2022-01-03,Inspection,232147,4.0,371.51,143.21,514.72,Dallas,14.0,Routine Inspection
9,MAINT00000010,TRK00076,2022-01-03,Inspection,222428,0.6,74.65,14.12,88.77,Columbus,23.0,Emergency Inspection

In [188]:
# Load dataset 'drivers'
df_drivers = pd.read_csv ("drivers.csv")

# Preview dataset 'drivers'
df_drivers. head (10)

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
0,DRV00001,Jennifer,Hernandez,2014-10-31,NaN,DL673510887,WA,1973-11-07,Denver,Active,A,3
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
2,DRV00003,Charles,Hernandez,2021-09-21,NaN,DL523076025,NC,1970-04-06,Salt Lake City,Active,A,19
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
4,DRV00005,Mary,Martinez,2018-12-02,NaN,DL706011277,AZ,1960-07-15,Chicago,Active,A,12
5,DRV00006,Robert,Taylor,2019-04-04,NaN,DL811890569,NC,1990-05-02,Portland,Active,A,23
6,DRV00007,James,Martinez,2019-07-02,2021-05-17,DL129100607,PA,1974-05-23,Miami,Terminated,A,5
7,DRV00008,Barbara,Wilson,2020-06-09,2021-01-23,DL190137896,CO,1978-12-28,Philadelphia,Terminated,A,15
8,DRV00009,Karen,Hernandez,2013-09-29,NaN,DL790147183,FL,1989-02-22,Los Angeles,Active,A,13
9,DRV00010,Sarah,Gonzalez,2020-11-08,NaN,DL560219456,WA,1974-05-26,Minneapolis,Active,A,23

In [189]:
# Load dataset 'trucks'
df_trucks = pd.read_csv ("trucks.csv")

# Preview dataset 'trucks'
df_trucks. head (10)

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
0,TRK00001,3463,Peterbilt,2016,1VV205190335317039,2017-04-27,18814,Diesel,200,Active,Omaha
1,TRK00002,6461,Kenworth,2015,1NV753749606229960,2018-10-04,26795,Diesel,150,Active,Seattle
2,TRK00003,2335,Peterbilt,2018,1NT803101860493229,2020-09-17,11795,Diesel,150,Maintenance,Atlanta
3,TRK00004,3317,Freightliner,2015,1VV131945381692351,2017-06-17,8875,Diesel,200,Active,Salt Lake City
4,TRK00005,6731,Freightliner,2016,1FT822215709701985,2021-10-08,42042,Diesel,250,Maintenance,Miami
5,TRK00006,6082,Kenworth,2017,1VV963516965177788,2018-05-12,47794,Diesel,150,Active,Minneapolis
6,TRK00007,7421,Volvo,2019,1MV134100489809236,2020-01-29,42328,Diesel,200,Active,Charlotte
7,TRK00008,3112,Mack,2015,1MV426140684859204,2015-01-27,27548,Diesel,150,Active,Houston
8,TRK00009,2388,International,2015,1VU871233565012431,2016-11-04,24540,Diesel,250,Active,Denver
9,TRK00010,6072,Volvo,2015,1MU182160377362421,2017-12-11,25066,Diesel,200,Active,Columbus

In [190]:
# Load dataset 'routes'
df_routes = pd.read_csv ("routes.csv")

# Preview dataset 'routes'
df_routes. head (10)

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
1,RTE00002,Atlanta,GA,Miami,FL,697,2.08,0.22,1
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3
3,RTE00004,Chicago,IL,Portland,OR,2017,1.84,0.19,3
4,RTE00005,Chicago,IL,Las Vegas,NV,1749,2.41,0.26,3
5,RTE00006,Chicago,IL,Charlotte,NC,675,2.13,0.28,1
6,RTE00007,Dallas,TX,New York,NY,1576,2.54,0.32,2
7,RTE00008,Dallas,TX,Denver,CO,762,2.62,0.15,1
8,RTE00009,Dallas,TX,Indianapolis,IN,878,1.95,0.17,1
9,RTE00010,New York,NY,Philadelphia,PA,92,1.61,0.17,1

## Data Understanding for each table or dataframe

In [191]:
# Dataset 'loads' understanding

In [192]:
# Basic Information about Dataset

df_loads.info ()

<class 'pandas.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   load_id              85410 non-null  str
 1   customer_id          85410 non-null  str
 2   route_id             85410 non-null  str
 3   load_date            85410 non-null  str
 4   load_type            85410 non-null  str
 5   weight_lbs           85410 non-null  int64
 6   pieces               85410 non-null  int64
 7   revenue              85410 non-null  float64
 8   fuel_surcharge       85410 non-null  float64
 9   accessorial_charges  85410 non-null  int64
 10  load_status          85410 non-null  str
 11  booking_type         85410 non-null  str
dtypes: float64(2), int64(3), str(7)
memory usage: 13.1 MB

In [193]:
# Statistical Summary on Dataset

df_loads.describe (include = 'all')

,load_id,customer_id,route_id,load_date,load_type,weight_lbs,pieces,revenue,fuel_surcharge,accessorial_charges,load_status,booking_type
count,85410,85410,85410,85410,85410,85410.000000,85410.000000,85410.000000,85410.000000,85410.000000,85410,85410
unique,85410,200,58,1096,2,NaN,NaN,NaN,NaN,NaN,1,3
top,LOAD00000001,CUST00181,RTE00047,2022-05-18,Refrigerated,NaN,NaN,NaN,NaN,NaN,Completed,Dedicated
freq,1,497,1628,108,42946,NaN,NaN,NaN,NaN,NaN,85410,42337
mean,NaN,NaN,NaN,NaN,NaN,27477.495305,14.470530,3073.712683,350.972119,71.643836,NaN,NaN
std,NaN,NaN,NaN,NaN,NaN,10095.421857,8.070077,1883.127436,218.034684,70.018823,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,10000.000000,1.000000,125.930000,13.800000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,NaN,18724.000000,7.000000,1443.215000,161.530000,0.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,NaN,27482.000000,14.000000,2827.985000,314.640000,50.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,NaN,36190.000000,21.000000,4323.157500,499.180000,100.000000,NaN,NaN
max,NaN,NaN,NaN,NaN,NaN,45000.000000,28.000000,8125.220000,891.820000,200.000000,NaN,NaN

In [194]:
# Check for missing values in Dataset

df_loads.isnull().sum()

load_id                0
customer_id            0
route_id               0
load_date              0
load_type              0
weight_lbs             0
pieces                 0
revenue                0
fuel_surcharge         0
accessorial_charges    0
load_status            0
booking_type           0
dtype: int64

In [195]:
# Check for duplicate rows (entire identical row) in Dataset

df_loads.duplicated ().sum ()

np.int64(0)

In [196]:
# Check for duplicate rows (based on Primary Key 'load_id') in Dataset

df_loads.duplicated (subset = ['load_id']).sum ()

np.int64(0)

In [197]:
# Check for duplicate rows (based on Primary Key 'load_id') in Dataset
# Alternate way

df_loads['load_id'].duplicated().sum()

np.int64(0)

In [198]:
# Dataset 'trips' understanding

In [199]:
# Basic Information about Dataset

df_trips.info ()

<class 'pandas.DataFrame'>
RangeIndex: 85410 entries, 0 to 85409
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   trip_id                85410 non-null  str
 1   load_id                85410 non-null  str
 2   driver_id              83696 non-null  str
 3   truck_id               83738 non-null  str
 4   trailer_id             83730 non-null  str
 5   dispatch_date          85410 non-null  str
 6   actual_distance_miles  85410 non-null  int64
 7   actual_duration_hours  85410 non-null  float64
 8   fuel_gallons_used      85410 non-null  float64
 9   average_mpg            85410 non-null  float64
 10  idle_time_hours        85410 non-null  float64
 11  trip_status            85410 non-null  str
dtypes: float64(4), int64(1), str(7)
memory usage: 13.3 MB

In [200]:
# Convert 'dispatch_date' column data type from strg to datetime

df_trips['dispatch_date'] = pd.to_datetime(df_trips['dispatch_date'], errors = 'coerce')

In [201]:
# Check whether data type has changed correctly

df_trips.dtypes

trip_id                             str
load_id                             str
driver_id                           str
truck_id                            str
trailer_id                          str
dispatch_date            datetime64[us]
actual_distance_miles             int64
actual_duration_hours           float64
fuel_gallons_used               float64
average_mpg                     float64
idle_time_hours                 float64
trip_status                         str
dtype: object

In [202]:
# # Statistical Summary on Dataset

df_trips. describe (include = 'all')

,trip_id,load_id,driver_id,truck_id,trailer_id,dispatch_date,actual_distance_miles,actual_duration_hours,fuel_gallons_used,average_mpg,idle_time_hours,trip_status
count,85410,85410,83696,83738,83730,85410,85410.000000,85410.000000,85410.000000,85410.000000,85410.000000,85410
unique,85410,85410,124,92,180,NaN,NaN,NaN,NaN,NaN,NaN,1
top,TRIP00000001,LOAD00000001,DRV00019,TRK00055,TRL00104,NaN,NaN,NaN,NaN,NaN,NaN,Completed
freq,1,1,749,977,514,NaN,NaN,NaN,NaN,NaN,NaN,85410
mean,NaN,NaN,NaN,NaN,NaN,2023-07-02 04:54:57.787144,1430.268130,25.014674,221.827422,6.501463,7.010783,NaN
min,NaN,NaN,NaN,NaN,NaN,2022-01-01 00:00:00,90.000000,1.400000,12.000000,5.500000,2.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,2022-09-30 00:00:00,717.000000,12.600000,111.800000,6.000000,4.500000,NaN
50%,NaN,NaN,NaN,NaN,NaN,2023-07-02 00:00:00,1297.500000,23.000000,204.500000,6.500000,7.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,2024-04-03 00:00:00,2147.000000,36.900000,326.400000,7.000000,9.500000,NaN
max,NaN,NaN,NaN,NaN,NaN,2024-12-31 00:00:00,3391.000000,67.800000,611.900000,7.500000,12.000000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,801.931973,14.191944,126.558874,0.578091,2.882488,NaN

In [203]:
# Check for missing values in Dataset

df_trips.isnull().sum()

trip_id                     0
load_id                     0
driver_id                1714
truck_id                 1672
trailer_id               1680
dispatch_date               0
actual_distance_miles       0
actual_duration_hours       0
fuel_gallons_used           0
average_mpg                 0
idle_time_hours             0
trip_status                 0
dtype: int64

In [204]:
# Fill the missing values in Dataset with "Unknown"

df_trips['driver_id'] = df_trips['driver_id'].fillna("Unknown")
df_trips['truck_id'] = df_trips['truck_id'].fillna("Unknown")
df_trips['trailer_id'] = df_trips['trailer_id'].fillna("Unknown")

In [205]:
# Check whether missing values filled in Dataset

df_trips.isnull().sum()

trip_id                  0
load_id                  0
driver_id                0
truck_id                 0
trailer_id               0
dispatch_date            0
actual_distance_miles    0
actual_duration_hours    0
fuel_gallons_used        0
average_mpg              0
idle_time_hours          0
trip_status              0
dtype: int64

In [206]:
# Check for duplicate rows (entire identical row) in Dataset

df_trips.duplicated ().sum ()

np.int64(0)

In [207]:
# Check for duplicate rows (based on Primary Key 'trip_id') in Dataset

df_trips.duplicated (subset = ['trip_id']).sum ()

np.int64(0)

In [208]:
# Dateset 'fuel_purchases' understanding

In [209]:
# Check the total number of rows and columns for 'fuel_purchases'

df_fuel_pur.shape

(196442, 11)

In [210]:
# Print the columns name

df_fuel_pur.columns

Index(['fuel_purchase_id', 'trip_id', 'truck_id', 'driver_id', 'purchase_date',
       'location_city', 'location_state', 'gallons', 'price_per_gallon',
       'total_cost', 'fuel_card_number'],
      dtype='str')

In [211]:
# Check the data type for each column of dataframe

df_fuel_pur.dtypes

fuel_purchase_id        str
trip_id                 str
truck_id                str
driver_id               str
purchase_date           str
location_city           str
location_state          str
gallons             float64
price_per_gallon    float64
total_cost          float64
fuel_card_number        str
dtype: object

In [212]:
# Convert column 'purchase_date' data type from stg to datetime

df_fuel_pur['purchase_date'] = pd.to_datetime(df_fuel_pur['purchase_date'], errors = 'coerce')

In [213]:
# Basic information about dataframe. you can see also whether data type has changed as expected

df_fuel_pur.info ()

<class 'pandas.DataFrame'>
RangeIndex: 196442 entries, 0 to 196441
Data columns (total 11 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   fuel_purchase_id  196442 non-null  str
 1   trip_id           196442 non-null  str
 2   truck_id          192562 non-null  str
 3   driver_id         192454 non-null  str
 4   purchase_date     196442 non-null  datetime64[us]
 5   location_city     196442 non-null  str
 6   location_state    196442 non-null  str
 7   gallons           196442 non-null  float64
 8   price_per_gallon  196442 non-null  float64
 9   total_cost        196442 non-null  float64
 10  fuel_card_number  196442 non-null  str
dtypes: datetime64[us](1), float64(3), str(7)
memory usage: 27.5 MB

In [214]:
# Statistical summary on dataset or dataframe

df_fuel_pur.describe ( include = 'all')

,fuel_purchase_id,trip_id,truck_id,driver_id,purchase_date,location_city,location_state,gallons,price_per_gallon,total_cost,fuel_card_number
count,196442,196442,192562,192454,196442,196442,196442,196442.000000,196442.000000,196442.000000,196442
unique,196442,76939,92,124,NaN,25,23,NaN,NaN,NaN,176645
top,FUEL00000001,TRIP00063973,TRK00044,DRV00108,NaN,Columbus,TN,NaN,NaN,NaN,FC107946
freq,1,11,2283,1722,NaN,7981,15690,NaN,NaN,NaN,5
mean,NaN,NaN,NaN,NaN,2023-07-04 01:09:17.642459,NaN,NaN,124.815660,3.898418,486.621965,NaN
min,NaN,NaN,NaN,NaN,2022-01-01 00:00:00,NaN,NaN,50.000000,3.150000,158.500000,NaN
25%,NaN,NaN,NaN,NaN,2022-10-01 16:00:00,NaN,NaN,87.200000,3.552000,336.240000,NaN
50%,NaN,NaN,NaN,NaN,2023-07-03 21:00:00,NaN,NaN,124.700000,3.856000,480.660000,NaN
75%,NaN,NaN,NaN,NaN,2024-04-05 00:00:00,NaN,NaN,162.400000,4.168000,625.530000,NaN
max,NaN,NaN,NaN,NaN,2025-01-02 23:00:00,NaN,NaN,200.000000,5.000000,997.900000,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,43.346522,0.436489,178.616665,NaN

In [215]:
# # Check for missing values in Dataset

df_fuel_pur.isnull().sum()

fuel_purchase_id       0
trip_id                0
truck_id            3880
driver_id           3988
purchase_date          0
location_city          0
location_state         0
gallons                0
price_per_gallon       0
total_cost             0
fuel_card_number       0
dtype: int64

In [216]:
# Fill the missing values in Dataset

# Merge only the columns we need from df_trips based on trip_id
# We use a 'left' join so we don't lose any rows from our fuel purchase table

df_fuel_pur = df_fuel_pur.merge(
    df_trips[['trip_id', 'truck_id', 'driver_id']], 
    on='trip_id', 
    how='left', 
    suffixes=('', '_from_trips')
)

# Use the pulled columns to fill the missing values in the original columns

df_fuel_pur['truck_id'] = df_fuel_pur['truck_id'].fillna(df_fuel_pur['truck_id_from_trips'])
df_fuel_pur['driver_id'] = df_fuel_pur['driver_id'].fillna(df_fuel_pur['driver_id_from_trips'])

# Drop the temporary columns we created during the merge

df_fuel_pur.drop(columns=['truck_id_from_trips', 'driver_id_from_trips'], inplace=True)

# Fill any absolute leftovers with 'Unknown'
df_fuel_pur['truck_id'] = df_fuel_pur['truck_id'].fillna('Unknown')
df_fuel_pur['driver_id'] = df_fuel_pur['driver_id'].fillna('Unknown')

In [217]:
# Check whether missing values filled

df_fuel_pur.isnull().sum()

fuel_purchase_id    0
trip_id             0
truck_id            0
driver_id           0
purchase_date       0
location_city       0
location_state      0
gallons             0
price_per_gallon    0
total_cost          0
fuel_card_number    0
dtype: int64

In [218]:
# Check for duplicate rows (entire identical row) in Dataset

df_fuel_pur.duplicated ().sum ()

np.int64(0)

In [219]:
# Check for duplicate rows (based on Primary Key 'fuel_purchase_id') in Dataset

df_fuel_pur.duplicated(subset = 'fuel_purchase_id').sum ()

np.int64(0)

In [220]:
# Dataset 'maintenance_records' Understanding

In [221]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

df_main_rec.sample(50)

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
2333,MAINT00002334,TRK00018,2024-05-23,Transmission,707673,6.8,593.72,1868.97,2462.69,Kansas City,8.3,Scheduled Transmission
1366,MAINT00001367,TRK00118,2023-05-13,Brake,72796,4.1,411.58,1338.43,1750.01,Seattle,25.4,Emergency Brake
1367,MAINT00001368,TRK00030,2023-05-14,Engine,326809,4.3,537.28,1690.65,2227.93,Atlanta,4.5,Scheduled Engine
2000,MAINT00002001,TRK00013,2024-01-06,Preventive,100342,2.4,211.91,758.55,970.46,Oklahoma City,2.0,Emergency Preventive
290,MAINT00000291,TRK00042,2022-04-17,Tire,701541,3.4,350.83,2166.26,2517.09,Nashville,28.2,Emergency Tire
1904,MAINT00001905,TRK00056,2023-11-28,Tire,570369,5.4,655.17,279.57,934.74,New York,37.4,Scheduled Tire
2223,MAINT00002224,TRK00019,2024-04-03,Engine,635678,0.6,66.58,431.37,497.95,Dallas,19.0,Scheduled Engine
1942,MAINT00001943,TRK00050,2023-12-11,Brake,435908,4.3,379.08,1806.34,2185.42,Salt Lake City,47.1,Routine Brake
2247,MAINT00002248,TRK00013,2024-04-12,Transmission,64378,7.0,814.93,3418.07,4233.00,Chicago,39.4,Routine Transmission
1343,MAINT00001344,TRK00082,2023-05-08,Tire,692423,2.6,303.78,3206.27,3510.05,Houston,10.8,Scheduled Tire
2421,MAINT00002422,TRK00091,2024-06-21,Brake,68603,6.3,629.92,2111.46,2741.38,Las Vegas,28.2,Scheduled Brake
625,MAINT00000626,TRK00054,2022-08-19,Preventive,368146,5.8,594.23,2018.86,2613.09,Chicago,13.3,Emergency Preventive
2185,MAINT00002186,TRK00077,2024-03-16,Brake,303555,1.2,144.83,1899.50,2044.33,Milwaukee,26.1,Scheduled Brake
2409,MAINT00002410,TRK00042,2024-06-17,Tire,202031,6.1,683.62,2101.91,2785.53,Detroit,7.4,Scheduled Tire
2439,MAINT00002440,TRK00088,2024-06-26,Preventive,544625,2.4,214.92,529.40,744.32,Detroit,27.4,Emergency Preventive
200,MAINT00000201,TRK00021,2022-03-18,Tire,238872,5.2,598.91,3128.50,3727.41,Oklahoma City,38.0,Emergency Tire
1895,MAINT00001896,TRK00114,2023-11-25,Transmission,598393,6.9,694.00,2463.23,3157.23,Salt Lake City,31.9,Emergency Transmission
2683,MAINT00002684,TRK00004,2024-10-04,Tire,349248,4.3,387.17,149.33,536.50,Columbus,22.5,Scheduled Tire
2225,MAINT00002226,TRK00052,2024-04-03,Inspection,640706,5.2,580.97,70.54,651.51,Philadelphia,29.6,Scheduled Inspection
2112,MAINT00002113,TRK00097,2024-02-17,Preventive,491879,2.7,253.01,2222.08,2475.09,Philadelphia,13.3,Routine Preventive
2148,MAINT00002149,TRK00108,2024-03-03,Preventive,68249,3.7,340.65,1788.43,2129.08,Las Vegas,36.0,Routine Preventive
271,MAINT00000272,TRK00079,2022-04-12,Engine,342458,5.2,589.31,2011.83,2601.14,Atlanta,38.2,Emergency Engine
1616,MAINT00001617,TRK00077,2023-08-20,Transmission,104910,6.3,685.45,1151.82,1837.27,New York,5.4,Scheduled Transmission
485,MAINT00000486,TRK00102,2022-06-30,Tire,228293,5.8,573.50,258.19,831.69,Memphis,2.5,Emergency Tire
2169,MAINT00002170,TRK00085,2024-03-10,Repair,188431,1.0,96.71,1551.04,1647.75,Charlotte,35.0,Scheduled Repair
446,MAINT00000447,TRK00063,2022-06-13,Tire,276332,3.3,371.96,189.64,561.60,Denver,11.8,Scheduled Tire
1772,MAINT00001773,TRK00086,2023-10-17,Preventive,746010,4.9,495.49,297.14,792.63,Denver,30.6,Emergency Preventive
1029,MAINT00001030,TRK00046,2023-01-14,Repair,350889,4.3,489.78,63.52,553.30,Dallas,36.5,Scheduled Repair
2614,MAINT00002615,TRK00045,2024-09-09,Brake,607583,1.9,200.50,3052.40,3252.90,Nashville,22.9,Emergency Brake
2141,MAINT00002142,TRK00094,2024-03-01,Transmission,351996,6.0,547.44,2011.48,2558.92,Houston,20.8,Scheduled Transmission
2663,MAINT00002664,TRK00009,2024-09-27,Preventive,591428,2.5,268.81,2559.50,2828.31,Portland,42.8,Scheduled Preventive
2322,MAINT00002323,TRK00008,2024-05-18,Transmission,399012,4.6,473.33,657.10,1130.43,Denver,42.4,Emergency Transmission
2481,MAINT00002482,TRK00111,2024-07-11,Transmission,607783,4.0,438.70,3049.07,3487.77,Phoenix,25.6,Emergency Transmission
81,MAINT00000082,TRK00102,2022-01-30,Transmission,683454,4.3,533.03,2309.25,2842.28,Los Angeles,18.9,Emergency Transmission
2438,MAINT00002439,TRK00048,2024-06-26,Repair,66820,6.7,776.72,2482.51,3259.23,Los Angeles,32.3,Scheduled Repair
309,MAINT00000310,TRK00025,2022-04-24,Tire,99529,7.1,877.67,3146.87,4024.54,Oklahoma City,21.4,Scheduled Tire
2042,MAINT00002043,TRK00115,2024-01-21,Engine,331595,6.2,551.38,931.73,1483.11,Portland,42.7,Routine Engine
1560,MAINT00001561,TRK00039,2023-07-29,Brake,649405,1.3,148.45,2190.58,2339.03,Chicago,15.7,Emergency Brake
1040,MAINT00001041,TRK00111,2023-01-18,Tire,294540,1.0,104.81,1804.87,1909.68,Omaha,3.4,Scheduled Tire
793,MAINT00000794,TRK00048,2022-10-19,Tire,297549,7.3,793.33,851.45,1644.78,Denver,2.2,Scheduled Tire
607,MAINT00000608,TRK00001,2022-08-13,Inspection,438267,2.9,359.50,23.07,382.57,Seattle,20.4,Emergency Inspection
422,MAINT00000423,TRK00070,2022-06-04,Engine,146834,4.2,443.07,596.45,1039.52,Minneapolis,35.4,Scheduled Engine
1541,MAINT00001542,TRK00038,2023-07-20,Engine,728611,4.1,427.96,3150.24,3578.20,Seattle,4.4,Emergency Engine
1238,MAINT00001239,TRK00023,2023-04-03,Brake,436411,7.5,838.20,1168.87,2007.07,Memphis,47.9,Emergency Brake
2175,MAINT00002176,TRK00092,2024-03-12,Preventive,339672,6.7,793.54,1704.67,2498.21,Nashville,12.2,Scheduled Preventive
707,MAINT00000708,TRK00058,2022-09-15,Inspection,560816,4.4,380.68,125.33,506.01,Detroit,30.9,Routine Inspection
591,MAINT00000592,TRK00106,2022-08-08,Inspection,96009,6.5,731.92,121.94,853.86,Indianapolis,35.6,Emergency Inspection
359,MAINT00000360,TRK00003,2022-05-10,Engine,448849,2.1,200.60,2441.23,2641.83,Portland,26.7,Scheduled Engine
2638,MAINT00002639,TRK00081,2024-09-18,Engine,558739,1.2,114.34,3113.57,3227.91,Memphis,6.6,Emergency Engine
2229,MAINT00002230,TRK00053,2024-04-05,Repair,440655,4.7,421.12,239.50,660.62,Atlanta,23.3,Scheduled Repair

In [222]:
df_main_rec.info ()

<class 'pandas.DataFrame'>
RangeIndex: 2920 entries, 0 to 2919
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   maintenance_id       2920 non-null   str
 1   truck_id             2920 non-null   str
 2   maintenance_date     2920 non-null   str
 3   maintenance_type     2920 non-null   str
 4   odometer_reading     2920 non-null   int64
 5   labor_hours          2920 non-null   float64
 6   labor_cost           2920 non-null   float64
 7   parts_cost           2920 non-null   float64
 8   total_cost           2920 non-null   float64
 9   facility_location    2920 non-null   str
 10  downtime_hours       2920 non-null   float64
 11  service_description  2920 non-null   str
dtypes: float64(5), int64(1), str(6)
memory usage: 456.8 KB

In [223]:
df_main_rec['maintenance_date'] = pd.to_datetime(df_main_rec['maintenance_date'], errors = 'coerce')

df_main_rec.dtypes

maintenance_id                    str
truck_id                          str
maintenance_date       datetime64[us]
maintenance_type                  str
odometer_reading                int64
labor_hours                   float64
labor_cost                    float64
parts_cost                    float64
total_cost                    float64
facility_location                 str
downtime_hours                float64
service_description               str
dtype: object

In [224]:
df_main_rec.describe (include = 'all')

,maintenance_id,truck_id,maintenance_date,maintenance_type,odometer_reading,labor_hours,labor_cost,parts_cost,total_cost,facility_location,downtime_hours,service_description
count,2920,2920,2920,2920,2920.000000,2920.000000,2920.000000,2920.000000,2920.000000,2920,2920.000000,2920
unique,2920,120,NaN,7,NaN,NaN,NaN,NaN,NaN,25,NaN,21
top,MAINT00000001,TRK00003,NaN,Inspection,NaN,NaN,NaN,NaN,NaN,Los Angeles,NaN,Scheduled Engine
freq,1,41,NaN,432,NaN,NaN,NaN,NaN,NaN,139,NaN,152
mean,NaN,NaN,2023-06-25 09:14:18.082191,NaN,401534.787671,4.178459,438.529825,1523.995271,1962.525096,NaN,24.736473,NaN
min,NaN,NaN,2022-01-01 00:00:00,NaN,50156.000000,0.500000,43.280000,0.140000,60.820000,NaN,2.000000,NaN
25%,NaN,NaN,2022-09-27 00:00:00,NaN,215376.500000,2.300000,242.600000,443.125000,906.752500,NaN,13.300000,NaN
50%,NaN,NaN,2023-06-22 12:00:00,NaN,407955.000000,4.200000,435.200000,1465.415000,1896.045000,NaN,24.750000,NaN
75%,NaN,NaN,2024-03-17 00:00:00,NaN,585079.000000,6.000000,622.382500,2489.445000,2938.257500,NaN,36.225000,NaN
max,NaN,NaN,2024-12-31 00:00:00,NaN,749875.000000,8.000000,976.870000,3498.610000,4426.570000,NaN,48.000000,NaN
std,NaN,NaN,NaN,NaN,207093.951665,2.131282,229.989621,1103.739471,1135.418952,NaN,13.312263,NaN

In [225]:
# Check for missing values in dataset

df_main_rec.isnull().sum()

maintenance_id         0
truck_id               0
maintenance_date       0
maintenance_type       0
odometer_reading       0
labor_hours            0
labor_cost             0
parts_cost             0
total_cost             0
facility_location      0
downtime_hours         0
service_description    0
dtype: int64

In [226]:
df_main_rec.duplicated().sum()

np.int64(0)

In [227]:
df_main_rec.duplicated(subset='maintenance_id').sum()

np.int64(0)

In [228]:
df_main_rec['maintenance_id'].duplicated().sum()

np.int64(0)

In [229]:
# Understanding of 'Driver' Dataset

In [230]:
df_drivers.sample (50)

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
105,DRV00106,Patricia,Williams,2014-11-19,2016-11-21,DL643271261,NC,1990-02-08,Indianapolis,Terminated,A,17
85,DRV00086,Karen,Moore,2019-05-24,2021-09-24,DL773496394,MI,1978-04-24,Los Angeles,Terminated,A,4
127,DRV00128,John,Thomas,2012-12-22,NaN,DL967797300,CA,1974-11-24,Las Vegas,Active,A,7
109,DRV00110,James,Gonzalez,2019-04-05,NaN,DL551034639,IL,1977-01-19,Kansas City,Active,A,3
3,DRV00004,Barbara,Brown,2013-09-08,NaN,DL735540030,WA,1995-02-06,Denver,Active,A,19
97,DRV00098,David,Anderson,2019-08-27,NaN,DL940348305,UT,1969-04-15,Kansas City,Active,A,5
94,DRV00095,Linda,Thomas,2020-03-06,NaN,DL229981882,MI,1965-10-28,Dallas,Active,A,10
59,DRV00060,Jessica,Thomas,2021-07-08,NaN,DL923450567,OK,1986-06-26,Oklahoma City,Active,A,6
19,DRV00020,Joseph,Martinez,2019-07-21,NaN,DL450948014,TX,1965-10-02,Houston,Active,A,18
49,DRV00050,Robert,Johnson,2020-11-09,NaN,DL356135680,OH,1974-02-15,Seattle,Active,A,11
44,DRV00045,Thomas,Martinez,2018-11-20,NaN,DL365518424,OH,1988-12-16,New York,Active,A,10
56,DRV00057,Thomas,Jackson,2015-03-27,NaN,DL599326438,FL,1984-04-20,Las Vegas,Active,A,23
71,DRV00072,William,Moore,2012-01-28,2014-05-03,DL216070149,NC,1984-07-22,Kansas City,Terminated,A,7
77,DRV00078,John,Taylor,2021-03-23,NaN,DL502982778,MO,1969-07-28,Minneapolis,Active,A,21
14,DRV00015,Susan,Wilson,2015-05-20,NaN,DL379340713,OH,1970-05-20,Salt Lake City,Active,A,21
115,DRV00116,Thomas,Hernandez,2014-04-15,2015-11-15,DL782454310,NC,1968-11-04,Salt Lake City,Terminated,A,8
68,DRV00069,Patricia,Taylor,2012-09-13,NaN,DL979717936,PA,1975-10-13,Minneapolis,Active,A,15
32,DRV00033,William,Anderson,2016-12-19,NaN,DL904258674,GA,1991-05-22,New York,Active,A,9
63,DRV00064,Michael,Smith,2020-08-08,NaN,DL752027025,OK,1991-03-15,Omaha,Active,A,4
17,DRV00018,Patricia,Martin,2021-09-01,NaN,DL327268503,PA,1985-05-17,Chicago,Active,A,5
69,DRV00070,Sarah,Anderson,2014-12-15,NaN,DL275842194,PA,1974-07-02,Indianapolis,Active,A,16
149,DRV00150,Robert,Martin,2015-09-16,NaN,DL506936666,CA,1983-02-22,Columbus,Active,A,14
76,DRV00077,Patricia,Anderson,2014-02-07,NaN,DL827296111,IN,1989-01-24,Detroit,Active,A,20
119,DRV00120,Jessica,Johnson,2018-05-14,NaN,DL264272995,TN,1965-05-11,Philadelphia,Active,A,10
35,DRV00036,Michael,Thomas,2012-12-04,NaN,DL475767056,TX,1976-06-04,Miami,Active,A,21
10,DRV00011,Michael,Martinez,2014-06-01,NaN,DL245706210,FL,1972-07-04,Dallas,Active,A,15
20,DRV00021,Patricia,Gonzalez,2019-05-25,2021-05-23,DL462388455,OK,1987-12-11,New York,Terminated,A,8
18,DRV00019,Robert,Jackson,2020-12-14,NaN,DL588229686,TX,1994-08-15,Seattle,Active,A,20
81,DRV00082,Michael,Anderson,2013-05-02,NaN,DL181600593,MI,1981-11-28,Charlotte,Active,A,7
98,DRV00099,Michael,Williams,2014-06-27,NaN,DL144097647,NE,1976-08-09,Salt Lake City,Active,A,13
74,DRV00075,John,Anderson,2015-07-13,NaN,DL434961542,TN,1981-02-28,Nashville,Active,A,25
148,DRV00149,Linda,Jones,2013-08-25,NaN,DL817461907,OK,1988-04-28,New York,Active,A,20
80,DRV00081,Joseph,Hernandez,2019-06-13,NaN,DL312954978,PA,1985-11-03,Chicago,Active,A,6
133,DRV00134,Linda,Moore,2015-08-23,NaN,DL986625773,MO,1983-02-22,Nashville,Active,A,18
126,DRV00127,Thomas,Gonzalez,2021-08-23,NaN,DL761330848,TX,1964-03-25,Portland,Active,A,15
64,DRV00065,Robert,Brown,2017-10-04,NaN,DL903079055,OH,1994-08-12,Denver,Active,A,25
146,DRV00147,Richard,Garcia,2020-06-09,NaN,DL711871397,IL,1986-05-02,Oklahoma City,Active,A,20
40,DRV00041,Karen,Martin,2020-03-19,NaN,DL799816232,TN,1983-10-25,Phoenix,Active,A,2
30,DRV00031,Charles,Anderson,2017-04-19,2019-07-18,DL604988121,NC,1980-11-04,Seattle,Terminated,A,10
135,DRV00136,Susan,Martin,2013-12-14,2014-12-19,DL736164778,NE,1995-06-20,Denver,Terminated,A,23
73,DRV00074,William,Brown,2017-12-12,NaN,DL127571992,OK,1968-09-19,Oklahoma City,Active,A,11
51,DRV00052,Thomas,Thomas,2017-09-28,2020-01-31,DL608482316,CO,1969-08-23,Phoenix,Terminated,A,13
141,DRV00142,John,Thomas,2012-01-31,NaN,DL399496923,TN,1975-09-05,Dallas,Active,A,15
48,DRV00049,John,Smith,2018-03-25,NaN,DL263619298,OK,1995-07-03,Memphis,Active,A,24
79,DRV00080,Richard,Martin,2014-08-03,NaN,DL867741192,CA,1976-06-20,Atlanta,Active,A,3
67,DRV00068,John,Garcia,2018-09-19,2019-04-08,DL935147672,AZ,1980-04-23,Los Angeles,Terminated,A,14
1,DRV00002,William,Martin,2020-10-02,NaN,DL128955006,GA,1976-11-03,Columbus,Active,A,20
26,DRV00027,Karen,Wilson,2013-12-22,2015-03-16,DL552651788,WI,1988-05-06,Philadelphia,Terminated,A,13
138,DRV00139,Sarah,Davis,2014-08-27,NaN,DL363598427,MN,1986-02-05,Charlotte,Active,A,14
114,DRV00115,Robert,Wilson,2014-10-29,2016-05-19,DL488896443,OR,1972-10-09,Salt Lake City,Terminated,A,2

In [231]:
df_drivers.info ()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   driver_id          150 non-null    str
 1   first_name         150 non-null    str
 2   last_name          150 non-null    str
 3   hire_date          150 non-null    str
 4   termination_date   26 non-null     str
 5   license_number     150 non-null    str
 6   license_state      150 non-null    str
 7   date_of_birth      150 non-null    str
 8   home_terminal      150 non-null    str
 9   employment_status  150 non-null    str
 10  cdl_class          150 non-null    str
 11  years_experience   150 non-null    int64
dtypes: int64(1), str(11)
memory usage: 24.8 KB

In [232]:
date_columns_in_df_drivers = ['hire_date', 'termination_date', 'date_of_birth']
df_drivers[date_columns_in_df_drivers] = df_drivers[date_columns_in_df_drivers].apply(pd.to_datetime, errors='coerce')
df_drivers.dtypes

driver_id                       str
first_name                      str
last_name                       str
hire_date            datetime64[us]
termination_date     datetime64[us]
license_number                  str
license_state                   str
date_of_birth        datetime64[us]
home_terminal                   str
employment_status               str
cdl_class                       str
years_experience              int64
dtype: object

In [233]:
df_drivers.describe (include = 'all')

,driver_id,first_name,last_name,hire_date,termination_date,license_number,license_state,date_of_birth,home_terminal,employment_status,cdl_class,years_experience
count,150,150,150,150,26,150,150,150,150,150,150,150.000000
unique,150,20,20,NaN,NaN,150,23,NaN,25,2,1,NaN
top,DRV00001,Thomas,Anderson,NaN,NaN,DL673510887,TX,NaN,Dallas,Active,A,NaN
freq,1,13,13,NaN,NaN,1,13,NaN,10,124,150,NaN
mean,NaN,NaN,NaN,2017-02-14 10:43:12,2017-10-18 21:13:50.769230,NaN,NaN,1979-05-03 20:38:24,NaN,NaN,NaN,13.493333
min,NaN,NaN,NaN,2012-01-28 00:00:00,2013-01-08 00:00:00,NaN,NaN,1960-05-24 00:00:00,NaN,NaN,NaN,2.000000
25%,NaN,NaN,NaN,2014-07-06 06:00:00,2015-03-24 06:00:00,NaN,NaN,1970-05-31 12:00:00,NaN,NaN,NaN,7.250000
50%,NaN,NaN,NaN,2017-07-14 12:00:00,2017-09-18 00:00:00,NaN,NaN,1979-06-22 12:00:00,NaN,NaN,NaN,13.500000
75%,NaN,NaN,NaN,2019-07-20 00:00:00,2020-10-09 18:00:00,NaN,NaN,1988-02-09 18:00:00,NaN,NaN,NaN,20.000000
max,NaN,NaN,NaN,2021-12-06 00:00:00,2022-05-05 00:00:00,NaN,NaN,1995-07-03 00:00:00,NaN,NaN,NaN,25.000000
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.958889

In [234]:
df_drivers.isnull().sum()

driver_id              0
first_name             0
last_name              0
hire_date              0
termination_date     124
license_number         0
license_state          0
date_of_birth          0
home_terminal          0
employment_status      0
cdl_class              0
years_experience       0
dtype: int64

In [235]:
df_drivers.duplicated().sum()

np.int64(0)

In [236]:
df_drivers['driver_id'].duplicated().sum()

np.int64(0)

In [237]:
# Understanding of Dataset 'df_trucks'

In [238]:
df_trucks.sample (50)

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
39,TRK00040,3527,International,2015,1VT932401669552606,2020-01-22,15051,Diesel,250,Active,Minneapolis
47,TRK00048,4891,Volvo,2015,1MT866431853044978,2015-07-04,7395,Diesel,150,Active,Las Vegas
43,TRK00044,8170,Volvo,2015,1FU446413094240484,2020-01-07,10166,Diesel,200,Active,Los Angeles
29,TRK00030,2264,Volvo,2015,1NU424938126853269,2016-04-14,49556,Diesel,200,Active,Salt Lake City
11,TRK00012,6381,Freightliner,2015,1MU483021764762154,2017-02-08,24739,Diesel,250,Active,Las Vegas
55,TRK00056,8684,Kenworth,2015,1MU294987034236724,2016-09-29,4409,Diesel,250,Inactive,Dallas
70,TRK00071,8873,Mack,2017,1NT854162115475075,2018-10-14,35373,Diesel,250,Active,Columbus
61,TRK00062,7256,Mack,2017,1NV650570590608475,2018-01-21,44041,Diesel,200,Active,Seattle
62,TRK00063,9239,Peterbilt,2015,1VU731052452964922,2016-04-24,46090,Diesel,200,Active,Portland
119,TRK00120,2821,Volvo,2017,1FT135731860465802,2019-03-06,35253,Diesel,250,Active,Kansas City
52,TRK00053,9749,Peterbilt,2015,1MV170122760242723,2020-04-23,1025,Diesel,150,Active,Las Vegas
94,TRK00095,7326,Mack,2015,1MU471127926628434,2016-05-06,3994,Diesel,150,Active,Houston
14,TRK00015,2531,International,2015,1VV219552826957760,2017-02-12,44743,Diesel,200,Active,Memphis
77,TRK00078,3626,Freightliner,2015,1FT746416854486193,2016-10-24,15346,Diesel,150,Active,Phoenix
37,TRK00038,3147,International,2015,1MV267690370888657,2019-02-18,34860,Diesel,250,Active,Atlanta
6,TRK00007,7421,Volvo,2019,1MV134100489809236,2020-01-29,42328,Diesel,200,Active,Charlotte
49,TRK00050,5668,Peterbilt,2015,1NT453185644930902,2015-09-03,43266,Diesel,150,Active,Columbus
27,TRK00028,3253,Kenworth,2015,1VU150939883819521,2020-09-21,14594,Diesel,150,Maintenance,Portland
41,TRK00042,3962,International,2019,1MV437535307599343,2020-04-15,30187,Diesel,200,Maintenance,Omaha
108,TRK00109,8685,Volvo,2015,1FT716597654505822,2017-06-02,24979,Diesel,250,Maintenance,Kansas City
69,TRK00070,1854,Kenworth,2015,1VT793191010829814,2017-11-13,15357,Diesel,200,Active,Oklahoma City
10,TRK00011,7171,Freightliner,2015,1FT567947164925037,2021-01-06,29395,Diesel,200,Active,Portland
50,TRK00051,8355,Mack,2016,1MT877433803899130,2018-05-19,27475,Diesel,250,Active,Columbus
57,TRK00058,7026,Mack,2015,1VV866452895220495,2018-08-10,38924,Diesel,200,Active,Columbus
113,TRK00114,5193,Volvo,2016,1MT248556276310965,2021-04-07,26755,Diesel,150,Active,Las Vegas
75,TRK00076,5670,Kenworth,2015,1NU637560149881760,2016-04-26,33023,Diesel,200,Active,Nashville
92,TRK00093,7126,Peterbilt,2015,1MU379279972794550,2018-02-25,19693,Diesel,200,Active,Denver
17,TRK00018,6928,International,2015,1FT570778303307847,2016-02-16,8715,Diesel,150,Active,Dallas
101,TRK00102,6493,Peterbilt,2015,1NT272470760513799,2016-02-21,27997,Diesel,200,Inactive,Minneapolis
115,TRK00116,3449,International,2019,1MV446968103715126,2020-12-10,19653,Diesel,200,Active,Kansas City
44,TRK00045,1715,Volvo,2015,1FV398961826922119,2016-06-18,18064,Diesel,200,Active,New York
89,TRK00090,1872,Volvo,2017,1NT680153134413264,2021-04-23,34160,Diesel,250,Active,Detroit
111,TRK00112,2298,Volvo,2016,1MT331261140931634,2021-06-01,45633,Diesel,200,Active,Minneapolis
88,TRK00089,7797,International,2019,1VU859309706861616,2020-04-24,43267,Diesel,250,Active,Las Vegas
104,TRK00105,1627,Volvo,2015,1MV847705711168299,2017-12-03,3072,Diesel,250,Active,Detroit
56,TRK00057,4178,Mack,2015,1MV715049377005134,2017-01-16,6612,Diesel,150,Active,Denver
1,TRK00002,6461,Kenworth,2015,1NV753749606229960,2018-10-04,26795,Diesel,150,Active,Seattle
84,TRK00085,4637,Kenworth,2015,1MT667695252589838,2018-05-26,21015,Diesel,250,Active,Dallas
74,TRK00075,3042,Mack,2015,1NT719643369337760,2015-05-05,9183,Diesel,250,Inactive,Phoenix
34,TRK00035,9626,International,2015,1VT778313629938960,2019-05-10,47126,Diesel,150,Active,Denver
8,TRK00009,2388,International,2015,1VU871233565012431,2016-11-04,24540,Diesel,250,Active,Denver
105,TRK00106,5700,Volvo,2017,1NT949762201559873,2017-10-27,22571,Diesel,200,Active,Atlanta
59,TRK00060,8564,Freightliner,2015,1NU436079292908621,2015-05-16,29257,Diesel,250,Active,Kansas City
73,TRK00074,9452,Volvo,2015,1MT967805362821388,2015-02-08,3699,Diesel,150,Active,Indianapolis
30,TRK00031,5846,Kenworth,2018,1FU607053119824892,2019-10-30,1489,Diesel,250,Active,New York
82,TRK00083,8167,Kenworth,2015,1FT739466077384341,2015-08-05,39185,Diesel,250,Active,Charlotte
114,TRK00115,4533,Peterbilt,2015,1MU165006752005085,2018-04-22,9779,Diesel,250,Active,Salt Lake City
58,TRK00059,8218,Mack,2015,1VV316468431256116,2018-12-03,2200,Diesel,150,Active,Dallas
31,TRK00032,2657,Mack,2015,1VV787975078730489,2018-01-31,19553,Diesel,250,Maintenance,Oklahoma City
0,TRK00001,3463,Peterbilt,2016,1VV205190335317039,2017-04-27,18814,Diesel,200,Active,Omaha

In [239]:
df_trucks.info ()

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   truck_id               120 non-null    str
 1   unit_number            120 non-null    int64
 2   make                   120 non-null    str
 3   model_year             120 non-null    int64
 4   vin                    120 non-null    str
 5   acquisition_date       120 non-null    str
 6   acquisition_mileage    120 non-null    int64
 7   fuel_type              120 non-null    str
 8   tank_capacity_gallons  120 non-null    int64
 9   status                 120 non-null    str
 10  home_terminal          120 non-null    str
dtypes: int64(4), str(7)
memory usage: 18.1 KB

In [240]:
df_trucks['acquisition_date'] = pd.to_datetime(df_trucks['acquisition_date'], errors = 'coerce')

df_trucks.dtypes

truck_id                            str
unit_number                       int64
make                                str
model_year                        int64
vin                                 str
acquisition_date         datetime64[us]
acquisition_mileage               int64
fuel_type                           str
tank_capacity_gallons             int64
status                              str
home_terminal                       str
dtype: object

In [241]:
df_trucks.describe (include = 'all')

,truck_id,unit_number,make,model_year,vin,acquisition_date,acquisition_mileage,fuel_type,tank_capacity_gallons,status,home_terminal
count,120,120.000000,120,120.000000,120,120,120.000000,120,120.000000,120,120
unique,120,NaN,6,NaN,120,NaN,NaN,1,NaN,3,24
top,TRK00001,NaN,Peterbilt,NaN,1VV205190335317039,NaN,NaN,Diesel,NaN,Active,Dallas
freq,1,NaN,24,NaN,1,NaN,NaN,120,NaN,92,10
mean,NaN,5568.641667,NaN,2015.891667,NaN,2018-05-04 14:24:00,26058.216667,NaN,201.666667,NaN,NaN
min,NaN,1086.000000,NaN,2015.000000,NaN,2015-01-27 00:00:00,227.000000,NaN,150.000000,NaN,NaN
25%,NaN,3306.000000,NaN,2015.000000,NaN,2016-10-22 18:00:00,14567.000000,NaN,150.000000,NaN,NaN
50%,NaN,5669.000000,NaN,2015.000000,NaN,2018-03-15 12:00:00,26060.500000,NaN,200.000000,NaN,NaN
75%,NaN,7812.500000,NaN,2017.000000,NaN,2020-02-22 12:00:00,38812.250000,NaN,250.000000,NaN,NaN
max,NaN,9991.000000,NaN,2021.000000,NaN,2021-10-08 00:00:00,49556.000000,NaN,250.000000,NaN,NaN
std,NaN,2563.782076,NaN,1.448243,NaN,NaN,14373.443614,NaN,39.922895,NaN,NaN

In [242]:
df_trucks.isnull().sum()

truck_id                 0
unit_number              0
make                     0
model_year               0
vin                      0
acquisition_date         0
acquisition_mileage      0
fuel_type                0
tank_capacity_gallons    0
status                   0
home_terminal            0
dtype: int64

In [243]:
df_trucks.duplicated().sum()

np.int64(0)

In [244]:
df_trucks['truck_id'].duplicated().sum()

np.int64(0)

In [245]:
# Understanding of 'df_routes' dataset

In [246]:
df_routes.sample (50)

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
26,RTE00027,Detroit,MI,Houston,TX,1271,2.02,0.33,2
7,RTE00008,Dallas,TX,Denver,CO,762,2.62,0.15,1
50,RTE00051,Memphis,TN,Los Angeles,CA,1840,1.85,0.25,3
38,RTE00039,Minneapolis,MN,Atlanta,GA,1044,2.08,0.33,1
6,RTE00007,Dallas,TX,New York,NY,1576,2.54,0.32,2
51,RTE00052,Memphis,TN,Minneapolis,MN,804,1.63,0.34,1
29,RTE00030,Seattle,WA,Indianapolis,IN,2147,2.48,0.33,3
33,RTE00034,Portland,OR,Columbus,OH,2332,2.12,0.34,4
47,RTE00048,Columbus,OH,Portland,OR,2332,2.69,0.34,4
4,RTE00005,Chicago,IL,Las Vegas,NV,1749,2.41,0.26,3
25,RTE00026,Miami,FL,Denver,CO,1984,1.72,0.28,3
16,RTE00017,Philadelphia,PA,Minneapolis,MN,1130,1.81,0.34,1
12,RTE00013,Phoenix,AZ,Denver,CO,673,1.70,0.21,1
22,RTE00023,Miami,FL,Dallas,TX,1276,2.33,0.17,2
52,RTE00053,Kansas City,MO,Atlanta,GA,777,2.35,0.27,1
8,RTE00009,Dallas,TX,Indianapolis,IN,878,1.95,0.17,1
44,RTE00045,Charlotte,NC,Memphis,TN,597,2.33,0.23,1
13,RTE00014,Phoenix,AZ,Kansas City,MO,1204,2.14,0.19,2
53,RTE00054,Kansas City,MO,Los Angeles,CA,1557,2.01,0.19,2
31,RTE00032,Portland,OR,Detroit,MI,2259,1.99,0.20,3
0,RTE00001,Atlanta,GA,Chicago,IL,677,1.70,0.19,1
43,RTE00044,Charlotte,NC,Portland,OR,2627,2.69,0.31,4
46,RTE00047,Columbus,OH,Philadelphia,PA,476,2.06,0.16,1
15,RTE00016,Philadelphia,PA,Seattle,WA,2729,2.50,0.17,4
28,RTE00029,Seattle,WA,Charlotte,NC,2623,2.47,0.34,4
54,RTE00055,Kansas City,MO,Miami,FL,1429,2.51,0.25,2
41,RTE00042,Charlotte,NC,Seattle,WA,2623,2.39,0.18,4
34,RTE00035,Las Vegas,NV,Dallas,TX,1229,1.69,0.28,2
20,RTE00021,Houston,TX,Portland,OR,2108,2.45,0.28,3
37,RTE00038,Las Vegas,NV,Kansas City,MO,1311,2.71,0.24,2
21,RTE00022,Houston,TX,Memphis,TN,557,1.95,0.29,1
36,RTE00037,Las Vegas,NV,New York,NY,2561,1.52,0.21,4
24,RTE00025,Miami,FL,Seattle,WA,3141,1.65,0.18,5
27,RTE00028,Seattle,WA,Houston,TX,2172,1.89,0.26,3
14,RTE00015,Philadelphia,PA,New York,NY,92,2.79,0.15,1
19,RTE00020,Houston,TX,Seattle,WA,2172,1.77,0.34,3
18,RTE00019,Houston,TX,Detroit,MI,1271,2.33,0.32,2
17,RTE00018,Philadelphia,PA,Indianapolis,IN,670,2.07,0.28,1
57,RTE00058,Kansas City,MO,Indianapolis,IN,519,2.27,0.19,1
42,RTE00043,Charlotte,NC,Denver,CO,1559,1.55,0.16,2
32,RTE00033,Portland,OR,Seattle,WA,167,2.42,0.24,1
5,RTE00006,Chicago,IL,Charlotte,NC,675,2.13,0.28,1
35,RTE00036,Las Vegas,NV,Los Angeles,CA,262,2.63,0.33,1
39,RTE00040,Minneapolis,MN,Los Angeles,CA,1749,2.38,0.30,3
10,RTE00011,New York,NY,Columbus,OH,547,1.69,0.24,1
45,RTE00046,Columbus,OH,Los Angeles,CA,2269,2.74,0.22,3
9,RTE00010,New York,NY,Philadelphia,PA,92,1.61,0.17,1
55,RTE00056,Kansas City,MO,Portland,OR,1718,2.47,0.18,2
2,RTE00003,Chicago,IL,Los Angeles,CA,2003,2.55,0.29,3
56,RTE00057,Kansas City,MO,Charlotte,NC,921,2.45,0.30,1

In [247]:
df_routes.info()

<class 'pandas.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   route_id                58 non-null     str
 1   origin_city             58 non-null     str
 2   origin_state            58 non-null     str
 3   destination_city        58 non-null     str
 4   destination_state       58 non-null     str
 5   typical_distance_miles  58 non-null     int64
 6   base_rate_per_mile      58 non-null     float64
 7   fuel_surcharge_rate     58 non-null     float64
 8   typical_transit_days    58 non-null     int64
dtypes: float64(2), int64(2), str(5)
memory usage: 5.8 KB

In [248]:
df_routes['origin_state'].unique()

<ArrowStringArray>
['GA', 'IL', 'TX', 'NY', 'AZ', 'PA', 'FL', 'MI', 'WA', 'CO', 'OR', 'NV', 'MN',
 'NC', 'OH', 'TN', 'MO']
Length: 17, dtype: str

In [249]:
df_routes['destination_state'].unique()

<ArrowStringArray>
['IL', 'FL', 'CA', 'OR', 'NV', 'NC', 'NY', 'CO', 'IN', 'PA', 'OH', 'MO', 'WA',
 'MN', 'MI', 'TN', 'TX', 'GA']
Length: 18, dtype: str

In [250]:
# Complete dictionary mapping including all unique origin and destination states
state_mapping = {
    'AZ': 'Arizona',        'CA': 'California',     'CO': 'Colorado', 
    'FL': 'Florida',        'GA': 'Georgia',        'IL': 'Illinois', 
    'IN': 'Indiana',        'MI': 'Michigan',       'MN': 'Minnesota', 
    'MO': 'Missouri',       'NC': 'North Carolina', 'NV': 'Nevada', 
    'NY': 'New York',       'OH': 'Ohio',           'OR': 'Oregon', 
    'PA': 'Pennsylvania',   'TN': 'Tennessee',      'TX': 'Texas', 
    'WA': 'Washington'
}

# Apply the mapping to both columns at the same time
state_cols = ['origin_state', 'destination_state']
df_routes[state_cols] = df_routes[state_cols].apply(lambda col: col.map(state_mapping))

# 3. Verify the changes
df_routes[state_cols].head()

  origin_state destination_state
0      Georgia          Illinois
1      Georgia           Florida
2     Illinois        California
3     Illinois            Oregon
4     Illinois            Nevada

In [251]:
# This should print 0 if every single state abbreviation was successfully replaced

print("Missing values after mapping:", df_routes[state_cols].isnull().sum().sum())

Missing values after mapping: 0

In [252]:
df_routes

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
0,RTE00001,Atlanta,Georgia,Chicago,Illinois,677,1.70,0.19,1
1,RTE00002,Atlanta,Georgia,Miami,Florida,697,2.08,0.22,1
2,RTE00003,Chicago,Illinois,Los Angeles,California,2003,2.55,0.29,3
3,RTE00004,Chicago,Illinois,Portland,Oregon,2017,1.84,0.19,3
4,RTE00005,Chicago,Illinois,Las Vegas,Nevada,1749,2.41,0.26,3
5,RTE00006,Chicago,Illinois,Charlotte,North Carolina,675,2.13,0.28,1
6,RTE00007,Dallas,Texas,New York,New York,1576,2.54,0.32,2
7,RTE00008,Dallas,Texas,Denver,Colorado,762,2.62,0.15,1
8,RTE00009,Dallas,Texas,Indianapolis,Indiana,878,1.95,0.17,1
9,RTE00010,New York,New York,Philadelphia,Pennsylvania,92,1.61,0.17,1
10,RTE00011,New York,New York,Columbus,Ohio,547,1.69,0.24,1
11,RTE00012,Phoenix,Arizona,Philadelphia,Pennsylvania,2389,2.71,0.19,4
12,RTE00013,Phoenix,Arizona,Denver,Colorado,673,1.70,0.21,1
13,RTE00014,Phoenix,Arizona,Kansas City,Missouri,1204,2.14,0.19,2
14,RTE00015,Philadelphia,Pennsylvania,New York,New York,92,2.79,0.15,1
15,RTE00016,Philadelphia,Pennsylvania,Seattle,Washington,2729,2.50,0.17,4
16,RTE00017,Philadelphia,Pennsylvania,Minneapolis,Minnesota,1130,1.81,0.34,1
17,RTE00018,Philadelphia,Pennsylvania,Indianapolis,Indiana,670,2.07,0.28,1
18,RTE00019,Houston,Texas,Detroit,Michigan,1271,2.33,0.32,2
19,RTE00020,Houston,Texas,Seattle,Washington,2172,1.77,0.34,3
20,RTE00021,Houston,Texas,Portland,Oregon,2108,2.45,0.28,3
21,RTE00022,Houston,Texas,Memphis,Tennessee,557,1.95,0.29,1
22,RTE00023,Miami,Florida,Dallas,Texas,1276,2.33,0.17,2
23,RTE00024,Miami,Florida,Philadelphia,Pennsylvania,1175,2.48,0.32,2
24,RTE00025,Miami,Florida,Seattle,Washington,3141,1.65,0.18,5
25,RTE00026,Miami,Florida,Denver,Colorado,1984,1.72,0.28,3
26,RTE00027,Detroit,Michigan,Houston,Texas,1271,2.02,0.33,2
27,RTE00028,Seattle,Washington,Houston,Texas,2172,1.89,0.26,3
28,RTE00029,Seattle,Washington,Charlotte,North Carolina,2623,2.47,0.34,4
29,RTE00030,Seattle,Washington,Indianapolis,Indiana,2147,2.48,0.33,3
30,RTE00031,Denver,Colorado,Kansas City,Missouri,640,2.19,0.29,1
31,RTE00032,Portland,Oregon,Detroit,Michigan,2259,1.99,0.20,3
32,RTE00033,Portland,Oregon,Seattle,Washington,167,2.42,0.24,1
33,RTE00034,Portland,Oregon,Columbus,Ohio,2332,2.12,0.34,4
34,RTE00035,Las Vegas,Nevada,Dallas,Texas,1229,1.69,0.28,2
35,RTE00036,Las Vegas,Nevada,Los Angeles,California,262,2.63,0.33,1
36,RTE00037,Las Vegas,Nevada,New York,New York,2561,1.52,0.21,4
37,RTE00038,Las Vegas,Nevada,Kansas City,Missouri,1311,2.71,0.24,2
38,RTE00039,Minneapolis,Minnesota,Atlanta,Georgia,1044,2.08,0.33,1
39,RTE00040,Minneapolis,Minnesota,Los Angeles,California,1749,2.38,0.30,3
40,RTE00041,Minneapolis,Minnesota,Houston,Texas,1216,2.75,0.21,2
41,RTE00042,Charlotte,North Carolina,Seattle,Washington,2623,2.39,0.18,4
42,RTE00043,Charlotte,North Carolina,Denver,Colorado,1559,1.55,0.16,2
43,RTE00044,Charlotte,North Carolina,Portland,Oregon,2627,2.69,0.31,4
44,RTE00045,Charlotte,North Carolina,Memphis,Tennessee,597,2.33,0.23,1
45,RTE00046,Columbus,Ohio,Los Angeles,California,2269,2.74,0.22,3
46,RTE00047,Columbus,Ohio,Philadelphia,Pennsylvania,476,2.06,0.16,1
47,RTE00048,Columbus,Ohio,Portland,Oregon,2332,2.69,0.34,4
48,RTE00049,Columbus,Ohio,Minneapolis,Minnesota,720,2.62,0.20,1
49,RTE00050,Columbus,Ohio,Kansas City,Missouri,712,1.94,0.24,1
50,RTE00051,Memphis,Tennessee,Los Angeles,California,1840,1.85,0.25,3
51,RTE00052,Memphis,Tennessee,Minneapolis,Minnesota,804,1.63,0.34,1
52,RTE00053,Kansas City,Missouri,Atlanta,Georgia,777,2.35,0.27,1
53,RTE00054,Kansas City,Missouri,Los Angeles,California,1557,2.01,0.19,2
54,RTE00055,Kansas City,Missouri,Miami,Florida,1429,2.51,0.25,2
55,RTE00056,Kansas City,Missouri,Portland,Oregon,1718,2.47,0.18,2
56,RTE00057,Kansas City,Missouri,Charlotte,North Carolina,921,2.45,0.30,1
57,RTE00058,Kansas City,Missouri,Indianapolis,Indiana,519,2.27,0.19,1

In [253]:
df_routes.describe (include = 'all')

,route_id,origin_city,origin_state,destination_city,destination_state,typical_distance_miles,base_rate_per_mile,fuel_surcharge_rate,typical_transit_days
count,58,58,58,58,58,58.000000,58.000000,58.000000,58.000000
unique,58,18,17,19,18,NaN,NaN,NaN,NaN
top,RTE00001,Kansas City,Texas,Los Angeles,California,NaN,NaN,NaN,NaN
freq,1,6,7,6,6,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,1391.500000,2.196724,0.248793,2.120690
std,NaN,NaN,NaN,NaN,NaN,782.833209,0.368788,0.061817,1.155879
min,NaN,NaN,NaN,NaN,NaN,92.000000,1.520000,0.150000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,700.750000,1.902500,0.190000,1.000000
50%,NaN,NaN,NaN,NaN,NaN,1271.000000,2.230000,0.245000,2.000000
75%,NaN,NaN,NaN,NaN,NaN,2085.250000,2.480000,0.300000,3.000000
max,NaN,NaN,NaN,NaN,NaN,3141.000000,2.790000,0.340000,5.000000

In [254]:
df_routes.isnull().sum()

route_id                  0
origin_city               0
origin_state              0
destination_city          0
destination_state         0
typical_distance_miles    0
base_rate_per_mile        0
fuel_surcharge_rate       0
typical_transit_days      0
dtype: int64

In [255]:
df_routes.duplicated().sum()

np.int64(0)

In [256]:
df_routes['route_id'].duplicated().sum()

np.int64(0)

Save the cleaned and transformed dataframes

In [257]:
import os

# Creates a folder on computer named 'cleaned_data'

os.makedirs('cleaned_data', exist_ok=True)

# Save cleaned DataFrames into that new folder as Parquet files

df_loads.to_parquet('cleaned_data/clean_loads.parquet')
df_trips.to_parquet('cleaned_data/clean_trips.parquet')
df_fuel_pur.to_parquet('cleaned_data/clean_fuel_pur.parquet')
df_main_rec.to_parquet('cleaned_data/clean_main_rec.parquet')
df_drivers.to_parquet('cleaned_data/clean_drivers.parquet')
df_trucks.to_parquet('cleaned_data/clean_trucks.parquet')
df_routes.to_parquet('cleaned_data/clean_routes.parquet')

print("Success! Your clean data is now saved inside the 'cleaned_data' folder.")

Success! Your clean data is now saved inside the 'cleaned_data' folder.